### ISSUE TITLE
Add a better readme file.

### ISSUE THREAD

**Issue by zippytyro** [zippytyro/Get-table#1]
**Visit the website - [here](https://get-table.now.sh/)**
Improve the readme file to add more details about the website.
Add a screenshot if necessary.

--------------------------------------
### How to contribute
- Fork this repo
- clone it to your own machine 
- create a new branch naming it as your username
- Edit the required files
- Commit and push

After that make PR
Thanks

**Comment by 0sf** [comment]
Can I work on this issue, please?

**Comment by zippytyro** [comment]
@0sf sure you can work
