### ISSUE TITLE
Improve the UI of the website (bootstrap)

### ISSUE THREAD

**Issue by zippytyro** [zippytyro/Get-table#2]
Visit the website - [here](https://get-table.now.sh)

The website made using bootstrap, improving the UI of the website.
Add copyright section in the footer etc.
You're free to make any required changes and use your creativity.
---------------------------------------------
### How to contribute
- Fork this repo
- clone it to your own machine 
- create a new branch naming it as your username
- Edit the required files
- Commit and push

After that make PR
Thanks

**Comment by clare0901** [comment]
Can i Contribute ??

**Comment by zippytyro** [comment]
@clare0901 sure you can

**Comment by clare0901** [comment]
@zippytyro Please add the hacktoberfest-accepted label !

**Comment by zippytyro** [comment]
@clare0901 The maintainers have to add, hacktoberfest topic OR hacktoberfest-accepted label.
Both are not necessary.
Read here - 
https://hacktoberfest.digitalocean.com/hacktoberfest-update
